export const ADD_BACK = 'analytics/ADD_BACK'
export const ADD_CONSENT_CHOICE_EVENT = 'ads/ADD_CONSENT_CHOICE_EVENT'
export const ADD_EVENT = 'analytics/ADD_EVENT'
export const ADD_EVENT_DEBOUNCED = 'analytics/ADD_EVENT_DEBOUNCED'
export const ADD_FOCUS = 'analytics/ADD_FOCUS'
export const ADD_KOCHAVA_EVENT = 'analytics/ADD_KOCHAVA_EVENT'
export const ADD_UNIQUE_EVENT = 'analytics/ADD_UNIQUE_EVENT'
export const CHANGE_KOCHAVA_ATTRIBUTION_STATUS = 'analytics/CHANGE_KOCHAVA_ATTRIBUTION_STATUS' // prettier-ignore
export const CLEAR_KOCHAVA_EVENT_BUFFER = 'analytics/CLEAR_KOCHAVA_EVENT_BUFFER' // prettier-ignore
export const COLLECT_DEBUG_INFO = 'analytics/COLLECT_DEBUG_INFO'
export const CONTINUE_SESSION = 'analytics/CONTINUE_SESSION'
export const LOG_EVENT = 'analytics/LOG_EVENT'
export const REHYDRATE = 'analytics/REHYDRATE'
export const REMOVE_AD = 'analytics/REMOVE_AD'
export const REMOVE_BACK = 'analytics/REMOVE_BACK'
export const REMOVE_FOCUS = 'analytics/REMOVE_FOCUS'
export const REMOVE_LAST_APP_VIEW = 'analytics/REMOVE_LAST_APP_VIEW'
export const RESET_ADS = 'analytics/RESET_ADS'
export const SEND_DEBUG_INFO = 'analytics/SEND_DEBUG_INFO'
export const SEND_DEBUG_INFO_ERROR = 'analytics/SEND_DEBUG_INFO_ERROR'
export const SEND_DEBUG_INFO_SUCCESS = 'analytics/SEND_DEBUG_INFO_SUCCESS'
export const SEND_EVENTS = 'analytics/SEND_EVENTS'
export const SEND_EVENTS_ERROR = 'analytics/SEND_EVENTS_ERROR'
export const SEND_EVENTS_SUCCESS = 'analytics/SEND_EVENTS_SUCCESS'
export const SET_APP_VIEW = 'analytics/SET_APP_VIEW'
export const SET_FIRST_AUTH_START_APP_VIEW = 'analytics/SET_FIRST_AUTH_START_APP_VIEW' // prettier-ignore
export const SET_IDFA_SENT_AT = 'app/SET_IDFA_SENT_AT'
export const START_SESSION = 'analytics/START_SESSION'
export const UPDATE_AD = 'analytics/UPDATE_AD'
export const SET_HAS_SEEN_COMPLETE_PROFILE_SLIDER = 'analytics/SET_HAS_SEEN_COMPLETE_PROFILE_SLIDER' // prettier-ignore
export const RESET_HAS_SEEN_COMPLETE_PROFILE_SLIDER = 'analytics/RESET_HAS_SEEN_COMPLETE_PROFILE_SLIDER' // prettier-ignore
export const SET_EVENT_HAS_USED_CURRENT_APP_OPEN_WITH_INTENT = 'analytics/SET_EVENT_HAS_USED_CURRENT_APP_OPEN_WITH_INTENT' // prettier-ignore
export const RESET_EVENT_HAS_USED_CURRENT_APP_OPEN_WITH_INTENT = 'analytics/RESET_EVENT_HAS_USED_CURRENT_APP_OPEN_WITH_INTENT' // prettier-ignore
export const SET_AUTH_START_TIME = 'analytics/SET_AUTH_START_TIME'
export const SET_HAS_VISITED_AUTH_HELP = 'analytics/SET_HAS_VISITED_AUTH_HELP'
