export const SET_ARE_ANALYTICS_ENABLED = '__app__/SET_ARE_ANALYTICS_ENABLED'

export const SET_IS_SIGNING_UP = '__app__/SET_IS_SIGNING_UP'

export const SET_NOT_ANONYMOUS_HINT_BANNER_SHOWN =
  '__app__/SET_NOT_ANONYMOUS_HINT_BANNER_SHOWN'

export const SET_STATIC_FRIENDS_COUNT = '__app__/SET_STATIC_FRIENDS_COUNT'
